# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/
# travis-ci.org specification for serf-cpp
# 
language: cpp
compiler:
  - gcc
  # - clang
os:
  - linux

sudo: required
dist: trusty

matrix:
  fast_finish: true
  include:

  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.9' ]

  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-6' ]

  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-7' ]

  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8' ] 


before_install:
  - eval "${MATRIX_EVAL}"

  # Install boost
  - sudo apt-get install -y libboost-all-dev

  # Install lcov
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  # install lcov to coveralls conversion + upload tool
  - gem install coveralls-lcov

  # Install google test 
  - wget https://github.com/google/googletest/archive/release-1.8.1.tar.gz -O /tmp/gtest.tar.gz
  - tar zxf /tmp/gtest.tar.gz
  - pushd googletest-* && mkdir build && cd build && cmake .. && sudo make install && popd

  # Install msgpack-c
  - wget https://github.com/msgpack/msgpack-c/releases/download/cpp-3.1.1/msgpack-3.1.1.tar.gz -O /tmp/msgpack-c.tar.gz
  - tar zxf /tmp/msgpack-c.tar.gz
  - pushd msgpack-3.1.1 && mkdir build && cd build && cmake .. && sudo make install && popd

script:
  - mkdir build
  - cd build
  - cmake -D SERF_CPP_BUILD_COVERAGE=TRUE .. && make
  - ./tests/SerfCppTests

after_success:
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveral


    
    
  
  

