# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/
# travis-ci.org specification for serf-cpp
# 
language: cpp
compiler:
  - gcc
  # - clang
os:
  - linux

sudo: required
dist: trusty

before_install:
  # Install boost
  - sudo apt-get install -y libboost-all-dev

  # Install lcov
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  # install lcov to coveralls conversion + upload tool
  - gem install coveralls-lcov

  # Install google test (gtest)
  - sudo apt-get install -y libgtest-dev

  - pushd /usr/src/gtest && sudo cmake . && sudo make && sudo mv libg* /usr/lib && sudo ldconfig && popd

  # Install msgpack-c
  - wget https://github.com/msgpack/msgpack-c/releases/download/cpp-1.4.2/msgpack-1.4.2.tar.gz -O /tmp/msgpack-c.tar.gz
  - tar zxf /tmp/msgpack-c.tar.gz
  - pushd msgpack-1.4.2 && ./configure --prefix=/usr && make && sudo make install && popd

script:
  - mkdir build
  - cd build
  - cmake -D SERF_CPP_BUILD_COVERAGE=TRUE .. && make
  - ./tests/SerfCppTests

after_success:
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveral

notifications:
  email:
    recipients:
      - cjlove@san.rr.com
    on_success: change
    on_failure: always

    
    
  
  

