name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        config:
          - { compiler: gcc, version: 4, build_type: Debug, cppstd: 11 }
          - { compiler: gcc, version: 5, build_type: Debug, cppstd: 11 }
          - { compiler: gcc, version: 6, build_type: Debug, cppstd: 11 }
          - { compiler: gcc, version: 7, build_type: Debug, cppstd: 11 }
          - { compiler: gcc, version: 8, build_type: Debug, cppstd: 11 }
          - { compiler: gcc, version: 9, build_type: Debug, cppstd: 11 }
          - { compiler: gcc, version: 10, build_type: Debug, cppstd: 11 }
          - { compiler: gcc, version: 11, build_type: Debug, cppstd: 11 }
          - { compiler: gcc, version: 12, build_type: Release, cppstd: 11 }

    container:
      image: ${{ matrix.config.compiler == 'clang' && 'teeks99/clang-ubuntu' || matrix.config.compiler }}:${{ matrix.config.version }}
    name: "${{ matrix.config.compiler}} ${{ matrix.config.version }} (C++${{ matrix.config.cppstd }}, ${{ matrix.config.build_type }})"
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          apt-get update && apt-get install -y curl git
          CMAKE_VERSION="3.24.2"
          curl -sSL https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh -o install-cmake.sh
          chmod +x install-cmake.sh
          ./install-cmake.sh --prefix=/usr/local --skip-license
          curl -sSL https://github.com/msgpack/msgpack-c/releases/download/cpp-3.1.1/msgpack-3.1.1.tar.gz -o /tmp/msgpack-c.tar.gz
          tar zxf /tmp/msgpack-c.tar.gz 
          pushd msgpack-3.1.1 && mkdir build && cd build && cmake .. && make install && popd
      - name: Setup Compiler
        if: matrix.config.compiler == 'clang'
        run: |
          if [[ "${{ matrix.config.version }}" -ge 4 ]]; then
            scripts/ci_setup_clang.sh "${{ matrix.config.version }}"
            echo "CXXFLAGS=-stdlib=libc++" >> $GITHUB_ENV
          fi
          echo "CC=clang-${{ matrix.config.version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ matrix.config.version }}" >> $GITHUB_ENV
      - name: Build
        run: |
          mkdir -p build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -DCMAKE_CXX_STANDARD=${{ matrix.config.cppstd }} \
            -DBUILD_EXAMPLES=${{ matrix.config.examples || 'ON' }} \
            -DBUILD_TESTS=ON 
          make -j2
          ctest -j2 --output-on-failure
